---

- hosts: localhost
  tasks:
  - name: Package domain testing utilities for later provisioning
    include_tasks: ./tasks/local.yml

- hosts: dc
  roles:
  - prepare-machine
  - samba-server
  - dc-test

- hosts: cl
  roles:
  - prepare-machine
  - samba-client
  - cl-test

- hosts: localhost
  tasks:
  - name: Analyze domain testing results
    command: "./diaganal '{{ playbook_dir }}/diag'"
    args:
      chdir: '{{ playbook_dir }}/util'

