---

- name: Add client hostname to /etc/hosts
  lineinfile:
    path: '/etc/hosts'
    state: present
    line: '10.64.6.100 {{ inventory_hostname | lower }}.{{ samba_realm | lower }} {{ inventory_hostname | lower }}'
  become: true

- name: Purge other resolv.conf`s
  command: >
    find /etc/net/ifaces -name resolv.conf -delete
  register: res
  changed_when: res.rc == 0
  failed_when: false
  become: true

- name: Set master DC as the 1st nameserver for clients
  template:
    src: resolv.conf.j2
    dest: /etc/net/ifaces/lo/resolv.conf
  vars:
    master_nameserver: 10.64.6.10
  become: true

- name: black magic
  shell: update_chrooted all
  changed_when: false
  become: true

- name: restart network service
  service:
    name: network
    state: restarted
  with_sequence: start=1 end=2
  become: true

- name: Generate /etc/krb.conf for Samba domain
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Generate Samba client configuration file
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  become: true

- name: Create OpenLDAP configuration directory
  file:
    path: /etc/openldap
    state: directory
  become: true

- name: Deploy stub OpenLDAP configuration
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
  become: true

- name: Join AD domain
  command: "/usr/sbin/system-auth write ad {{ samba_realm | upper }} {{ inventory_hostname }} {{ samba_domain | upper }} 'Administrator' '{{ admin_pass }}'"
  become: true

