---

- name: Purge other resolv.conf`s
  command: >
    find /etc/net/ifaces -name resolv.conf -delete
  register: res
  changed_when: res.rc == 0
  failed_when: false
  become: true

- name: Set localhost as the nameserver for controllers
  template:
    src: resolv.conf.j2
    dest: /etc/net/ifaces/lo/resolv.conf
  vars:
    master_nameserver: '127.0.0.1'
  become: true

- name: black magic
  shell: update_chrooted all
  changed_when: false
  become: true

- name: restart network service
  service:
    name: network
    state: restarted
  with_sequence: start=1 end=2
  become: true

- name: Deploy Samba Domain Controller configuration
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  become: true

- name: Generate /etc/krb.conf for Samba domain
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create OpenLDAP configuration directory
  file:
    path: /etc/openldap
    state: directory
  become: true

- name: Deploy stub OpenLDAP configuration
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
  become: true

- name: Deploy Samba Domain Controller
  command: "samba-tool domain provision --realm={{samba_realm|upper}} --domain={{samba_domain|upper}} --adminpass='{{ admin_pass }}' --dns-backend=SAMBA_INTERNAL --server-role=dc --use-rfc2307 --host-ip={{ ansible_host }}"
  become: true

- name: Enable and start Samba service
  service:
    name: samba
    enabled: true
    state: started
  become: true

